### ISSUE TITLE
adding new cities to the list on homepage

### ISSUE THREAD

**Issue by Katearmstrong4** [fabcity/newfabcity#15]
Hi @tuengominh! 
We need to update some info on the site. Super simple stuff. 
On the list of cities can we please add:

Plymouth
Hamburg
Yucatàn Region
Rennes
São Paolo 
Recife

They all joined the network in 2019 

Thank you!

**Comment by viktorsmari** [comment]
@Katearmstrong4 can you please give me **write access** to this repository?
Then I don't need to create pull requests.

I added the cities in Pull Request #16 which you will need to merge
